version: "3.8"
services:
  api:
    container_name: quiz_api
    build:
      context: ./
      dockerfile: docker/Dockerfile-api
    ports:
      - "8081:8080"
    volumes:
      - /api/node_modules
      - ./api:/api:delegated
      - ./db:/db
    networks:
      - quiz
  app:
    container_name: quiz_app
    build:
      context: ./
      dockerfile: docker/Dockerfile-app
    volumes:
      - /app/node_modules
      - ./app:/app:delegated
    ports:
      - "8080:3000"
    links:
      - api
    stdin_open: true
    tty: true
    networks:
      - quiz
networks:
  quiz:
    driver: bridge
